### PR TITLE
Add code of conduct 1

### PR DESCRIPTION
**Pull request by IanoNjuguna**

### CODE REVIEW

**Comment by IanoNjuguna** [comment]
@galadhremmin  I'm requesting for you to suggest iterations to the Code of Conduct.md for us to make it suit the needs of this project.

**Comment by galadhremmin** [comment]
First pull request! 👊 Are you proposing that we apply this code to the Parf Edhellen community or the developer community?

Also, please target the master branch as the `parf-edhellen-prod` branch is tied to elfdict.com's production environment.

**Comment by IanoNjuguna** [comment]
> First pull request! fist_oncoming Are you proposing that we apply this code to the Parf Edhellen community or the developer community?
> 
> Also, please target the master branch as the `parf-edhellen-prod` branch is tied to elfdict.com's production environment.

My bad, I'll correct the branching.
I intended it to be for the developer community but I'm open to making it inclusive to the Parf Edhellen community too. That depends on:
* Should it be for both communities?
* What should I add and remove to make it so?

**Comment by galadhremmin** [comment]
So I've been agonizing over this for some time now and I'm not sure what to make of these guidelines. I'm pretty much sure that most of it is already part of [the community guidelines for Github](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) so what is the incremental value you were looking for?

**Comment by IanoNjuguna** [comment]
Sure thing.

**Pull request closed without merging**
